name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: make

      - run: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.37.1/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/ && rm -rf skaffold

      - run: sudo mkdir -p out/manifest && skaffold render --default-repo=fengye87 --offline=true --digest-source=tag | sudo tee out/manifest/hello.yaml

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - uses: docker/build-push-action@v2
        with:
          file: build/image/Dockerfile.hello
          platforms: linux/amd64,linux/arm64
          tags: fengye87/hello:${{ steps.get_version.outputs.version }}
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: build/image/Dockerfile.helloctl
          platforms: linux/amd64,linux/arm64
          tags: fengye87/helloctl:${{ steps.get_version.outputs.version }}
          push: true

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            out/dist/*.tar.gz
            out/rpm/*.rpm
            out/manifest/*.yaml

  release-arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - run: docker build --platform linux/arm64 -f build/dist/Dockerfile . | tee /dev/tty | tail -n1 | cut -d' ' -f3 | xargs -I{} docker run --platform linux/arm64 --rm -v $PWD:/workspace -w /workspace {} build/dist/build.sh

      - run: docker build --platform linux/arm64 -f build/rpm/Dockerfile . | tee /dev/tty | tail -n1 | cut -d' ' -f3 | xargs -I{} docker run --platform linux/arm64 --rm -v $PWD:/workspace -w /workspace {} build/rpm/build.sh

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            out/dist/*.tar.gz
            out/rpm/*.rpm
